language: node_js

node_js:
  - "0.10"
  - "0.11"

matrix:
  allow_failures:
    - node_js: "0.11"

install:
  - npm install -g phantomjs@^1.9.7-15 gulp bower
  - npm install
  - bower install
  - echo -n | GITLAB_URL=http://127.0.0.1 LABOARD_PORT=4242 gulp app

script:
  - gulp atoum
  - npm start > /dev/null 2>&1 &
  - sleep 5
  - gulp karma:ci karma
  - gulp protractor

after_script:
  - kill %1
