language: node_js

node_js:
  - "0.10"
  - "0.11"

matrix:
  allow_failures:
    - node_js: "0.11"

install:
  - npm install -g phantomjs@^1.9.7-15

script:
  - node_modules/gulp/bin/gulp.js atoum
  - node_modules/gulp/bin/gulp.js server > /dev/null 2>&1 &
  - sleep 5
  - node_modules/gulp/bin/gulp.js karma:ci karma
  - node_modules/gulp/bin/gulp.js protractor

after_script:
  - kill %1
