language: node_js

node_js:
  - "0.10"
  - "0.11"

matrix:
  allow_failures:
    - node_js: "0.11"

env:
  - GULP_COMMAND=atoum
  - GULP_COMMAND=karma:ci karma
  - GULP_COMMAND=protractor

install:
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then npm install -g phantomjs@^1.9.7-15 gulp bower; else true; fi;'
  - npm install
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then bower install; else true; fi;'
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then echo -n | GITLAB_URL=http://127.0.0.1 LABOARD_PORT=4242 gulp app; else true; fi;'

script:
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then npm start > /dev/null; else true; fi;' &
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then sleep 5; else true; fi;'
  - gulp $GULP_COMMAND

after_script:
  - sh -c 'if [ "$GULP_COMMAND" != "atoum" ]; then kill %1; else true; fi;'
